### ISSUE TITLE
 As a user, I want the form to alert me when entering an invalid input and I want to utilize a calendar when submitting dates

### ISSUE THREAD

**Issue by AirZT11** [the-collab-lab/tcl-27-smart-shopping-list#22]
**Extra User Story**

AC:

* Warn user when an item isn't entered or a frequency isn't selected
* Use react-datepicker to display a calendar when a user wants to pick a date for last purchased
* Calendar dates should be sent to the backend as a consistent date format
* Clear form when form is submitted

_Note: This issue is for extra implied features the team wanted to implement_

**Comment by grellyd** [comment]
Small issue feedback: user stories take the form `As a __, I want to___, so that/because ____.`. In this case, you are missing the latter part, the 'because', which is arguably the most important part!
